#!/bin/bash

# This hook tags a newly pushed image with 'latest'
set -e

repoName=$(awk -F: '{ print $1 }' <<< ${IMAGE_NAME})

docker tag ${IMAGE_NAME} ${repoName}:latest
echo "Successfully tagged ${repoName}:latest"
docker push ${repoName}:latest 1>&2
echo "Successfully pushed ${repoName}:latest"
